### ISSUE TITLE
generic vocab for IKMT to be used with MOF/eMoF

### ISSUE THREAD

**Issue by ymgan** [nvs-vocabs/OBISVocabs#17]
## MeasurementType

I have a dataset with IKMT which does not seem to fit any of the existing vocab as the definition is extremely specific: https://vocab.nerc.ac.uk/search_nvs/L22/?searchstr=ikmt&options=identifier,preflabel,altlabel,status_accepted&rbaddfilter=inc&searchstr2=

## Issue

I am wondering if it is possible to create a generic vocab for IKMT which could be the parent of all available IKMT vocab, so that I can specify the other parameters of the net using other `measurementType`? For example:

measurementTypeID | measurementType | measurementValueID | measurementValue | measurementUnitID | measurementUnit
:--|:--|:--|:--|:--|:--
https://vocab.nerc.ac.uk/collection/Q01/current/Q0100002/ | Sampling instrument name | | Isaacs-Kid Midwater Trawl net | |
https://vocab.nerc.ac.uk/collection/Q01/current/Q0100015/ | Sampling net mesh size | | 0.505 | https://vocab.nerc.ac.uk/collection/P06/current/UXMM/ | Millimetres
| | Size of codend mesh | | 0.505 | https://vocab.nerc.ac.uk/collection/P06/current/UXMM/ | Millimetres
https://vocab.nerc.ac.uk/collection/Q01/current/Q0100017/ | Sampling device aperture surface area | | 2.54 | https://vocab.nerc.ac.uk/collection/P06/current/UMSQ/ | Square metres

**Comment by gwemon** [comment]
Hi @ymgan http://vocab.nerc.ac.uk/collection/L22/current/NETT0071/ does say that the specific measurements are for the original one hence it could be used for IKMT gears similar in design but with different dimension. 
Current definition is "A trawl with a pentagonal mouth opening and a dihedral depressor vane as part of the mouth opening. The original IKMTs were 10 foot (304 cm), and 15 foot (457 cm) at the mouth. The 10 foot IKMT net was 31 feet (9.45 m) in length [Wiebe and Benfield 2003 Plate 3 D]."
Or is the first sentence too specific too?
It is possible to propose a new more generic one if you feel this is not adequate and there is a risk of confusion. Please submit your suggestion for the definition of the new entry to L22 [here](https://github.com/nvs-vocabs/L22/issues/new?assignees=&labels=New+term&template=request-new-term.md&title=NTR%3A)
Many thanks, Gwen.

**Comment by ymgan** [comment]
Hey Gwen, I am so sorry! I totally forgot about this! I am going for the solution as you suggested to use the original one. Thank you so much!
