### ISSUE TITLE
MoF difficulty in finding P01 code for sex/gender

### ISSUE THREAD

**Issue by EliLawrence** [nvs-vocabs/OBISVocabs#20]
## MeasurementType
gender or sex

## Issue
Similar to lifestage (issue #19 ). A P01 code exists for gender (http://vocab.nerc.ac.uk/collection/P01/current/ENTSEX01/) but OBIS uses the term "sex" so users may have difficulty finding this P01 code when searching. Suggest adding "sex" as an additional alternative label.

**Comment by derek-mba** [comment]
Surely this is correctly​ "sex". "Gender" is a term we have developed, in the sense this is used, specifically to apply to humans. If fish have a concept of gender, we don't know what it is!
________________________________
From: Elizabeth ***@***.***>
Sent: 21 July 2022 17:09
To: nvs-vocabs/OBISVocabs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvs-vocabs/OBISVocabs] MoF difficulty in finding P01 code for sex/gender (Issue #20)

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


MeasurementType

gender or sex

Issue

Similar to lifestage (issue #19<https://github.com/nvs-vocabs/OBISVocabs/issues/19> ). A P01 code exists for gender (http://vocab.nerc.ac.uk/collection/P01/current/ENTSEX01/) but OBIS uses the term "sex" so users may have difficulty finding this P01 code when searching. Suggest adding "sex" as an additional alternative label.

**Comment by gwemon** [comment]
I totally agree with you @derek-mba. A few years ago I changed the description of S10 to refer to "sex categories" instead of "gender" because I thought "gender" was not really appropriate for what the S10 terms were for. What should we do with the term "gender" though? Shall we keep both associated with ENTSEX01 somehow? or shall we remove it completely?

**Comment by EliLawrence** [comment]
I agree as well. I don't think I see an issue with keeping both associated with ENTSEX01. The title could simply be "Sex of biological entity specified elsewhere" and the definition could be modified to something like "The identified sex or gender of the biological object." 
So sex would be the main focus but gender could be kept in case human related datasets want to use it? Perhaps it would be confusing to use both in the same term though, in which case maybe dropping the term "gender" would be a better solution.

**Comment by gwemon** [comment]
I somehow feel that the 2, sex and gender, are distinct concepts hence why we should probably drop the use of "gender" altogether. The definition of Sex of biological entity specified elsewhere could be: "Sexual category of an organism or group of organisms named elsewhere in the data schema. The sex is determine according to protocols which may vary depending on the type of organism and which are based on the observation of known biological characteristics."

**Comment by EliLawrence** [comment]
To follow up on this - agreed that sex and gender are different concepts. That definition seems good to me. Have any actions been taken to add a P01 code for sex as you've described it? We can also discuss it at the next OBIS Vocab meeting if you'd like. Thanks Gwen!

**Comment by gwemon** [comment]
See also: https://en.wikipedia.org/wiki/Sex

**Comment by gwemon** [comment]
I have updated ENTSEX01 and queued the changes for publication tomorrow.

**Comment by danibodc** [comment]
Updates live on the NVS:
https://vocab.nerc.ac.uk/collection/P01/current/ENTSEX01/
