### ISSUE TITLE
MoF Parameters associated with green tide monitoring 

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/OBISVocabs#21]
BODC has just received a request for parameter codes for a submission of green tide monitoring data to EMODnet biology.
The observations and associated variables are:
  * Surface of the studied area impacted by the green tide pollution (2 parameters depending of the Ulva morphology)
     * Surface impacted by Ulva (ITIS: 1753: WoRMS 1944296) in blade, (by GIS calculation, unit: square metres)
     * Surface impacted by Ulva (ITIS: 1753: WoRMS 1944296) in blade + filamentous , by GIS calculation, unit: square metres
  * Theoretical surface covered by the green tide pollution as equivalent to 100% coverage, by GIS calculation, unit: square metres
     * Theoretical surface covered by Ulva (ITIS: 1753: WoRMS 1944296) in blade as equivalent to 100% coverage, by GIS calculation, unit: square metres
     * Theoretical surface covered by Ulva (ITIS: 1753: WoRMS 1944296) in blade + filamentous as equivalent to 100% coverage, by GIS calculation, unit: square metres
  * Type of stranding of the green tide pollution
     * Type of stranding of Ulva (ITIS: 1753: WoRMS 1944296) (visual evaluation, 3 values (free text) :'continuous carpet of Ulva','>30% of the total algae deposition','<30% of the total algae deposition', no unit)

I asked for more information about the definition of "theoretical surface" and this is how it is defined:
The sum of the areas covered by the Taxon multiplied by coverage ratio, resulting in an area equivalent to a 100% coverage rate. Example: Area of the water covered by the Taxon =  2 000m², coverage ration = 50%, => theoretical surface = 1 000 m² (2 000m²*0,5). We were given a link to the protocol document for the methodology (https://www.aquaref.fr/system/files/2012_IA04_Point2.4_IFREMER_guide_methodologique_VF.pdf). It is in french. I would welcome advice about the equivalent term in english for this "theoretical surface" parameter.

Also how would you recommend handling this kind of data in OBIS? Would the genus responsible (i.e. Ulva) go in the occurrence core? In that case where would the distinction between the 2 morphotypes go?

**Comment by auspex** [comment]
With respect to OBIS, the way we would generally handle morphologies in plankton, where our own data might have adult and larval stages (or male & female) of a species, is to use species (or Genus -- any valid Aphia) in the occurrence and add LifeStage/Sex to the eMOF (though, to be honest, EurOBIS wasn't terribly thrilled with me about that, because it meant we might have multiple occurrence records for the same Aphia in a single Event). I haven't the slightest idea if the same concept would work with algae!

**Comment by gwemon** [comment]
Thank you @auspex. @nvs-vocabs/obis_vocabs could anybody else help with this request?

**Comment by gwemon** [comment]
This request is quite urgent so I will have to go ahead and create the parameter codes as best I can. See https://github.com/nvs-vocabs/P01/issues/190
