### ISSUE TITLE
Mean count of biological entity

### ISSUE THREAD

**Issue by EliLawrence** [nvs-vocabs/OBISVocabs#29]
## MeasurementType request
mean count of biological entity specified elsewhere
A combination of these two, but not seasonal: https://vocab.nerc.ac.uk/collection/P01/current/OCOUNT01/ and https://vocab.nerc.ac.uk/collection/P01/current/SOVO0002/

## Issue
We have a request for a P01 code for the mean count of biological entity specified elsewhere. Currently there is only a P01 for "count" and for a seasonal mean. Ideally we would like to use a new "mean count" code in cases where the mean was averaged from multiple observers, but also be used if it's a generic mean of a count. Hopefully that is possible. Mappings could include:

S25:BE007117 | biological entity specified elsewhere
S06:S0600008 | Count
S07:S0700003 | mean
S26:MAT00906 | not applicable 
P02:BPRP | SeaDataNet biological format biotic parameters
P06:UUUU | Dimensionless 
S02:S029 | not applicable

@ymgan please add any details I may have missed
Thanks!

**Comment by roswri** [comment]
New code created: https://vocab.nerc.ac.uk/collection/P01/current/OCNTMEAN/ - Count mean of biological entity specified elsewhere
This should be live on the NVS early tomorrow.

**Comment by EliLawrence** [comment]
Thanks @roswri!
